In [1]:
import pandas as pd

In [10]:
p = "/home/jiit_2404170001/Downloads/job1/gpu-dev-container/validation_test_split/queries_test.tsv"

In [11]:
d = pd.read_csv(p, sep="\t", header=None)

In [12]:
d.head()

         0                                          1
0  1000000          where does real insulin come from
1  1000003                     where does parrot live
2  1000004             where does name nora come from
3  1000006  where does most of the iron ore come from
4  1000012                        where is weston, fl

In [13]:
d.columns= ["queruy_id", "query"]

In [14]:
d.head()

   queruy_id                                      query
0    1000000          where does real insulin come from
1    1000003                     where does parrot live
2    1000004             where does name nora come from
3    1000006  where does most of the iron ore come from
4    1000012                        where is weston, fl

In [16]:
d["queruy_id"].nunique()

52378

In [18]:
ap = "/home/jiit_2404170001/Downloads/job1/gpu-dev-container/validation_test_split/queries_validation.tsv"

In [20]:
ad = pd.read_csv(ap, sep="\t", header=None)

In [21]:
ad.columns= ["queruy_id", "query"]

In [22]:
ad["queruy_id"].nunique()

3200

In [30]:
add = "/home/jiit_2404170001/Downloads/job1/gpu-dev-container/inputs/queries.dev.small.tsv"

In [31]:
pdd = pd.read_csv(add, sep="\t", header=None)

In [32]:
pdd.columns = ["queruy_id","query"]

In [33]:
pdd["queruy_id"].nunique()

55578

In [34]:
qv = "/home/jiit_2404170001/Downloads/job1/gpu-dev-container/validation_test_split/validation.tsv"
qvd = pd.read_csv(qv, sep="\t", header=None)
qvd.head()

,0,1,2,3
0,598962,1782646,what colors make lime green,Lime green and golden yellow are two of the mo...
1,846223,3010593,what is the second trimesters divided,From 12 weeks to 27 weeks the fetus continues ...
2,340006,6651435,how soon together for epidural injections,Epidural steroid injections may be repeated as...
3,992417,7187154,whitney wolfe net worth,John Salley Net Worth; Rochelle Aytes Net Wort...
4,998899,3086809,definition eaves,Eaves are the horizontal section of a roof tha...

In [35]:
qvd.columns = ["query_id", "query", "passage_id", "passage"]

In [36]:
qvd

,query_id,query,passage_id,passage
0,598962,1782646,what colors make lime green,Lime green and golden yellow are two of the mo...
1,846223,3010593,what is the second trimesters divided,From 12 weeks to 27 weeks the fetus continues ...
2,340006,6651435,how soon together for epidural injections,Epidural steroid injections may be repeated as...
3,992417,7187154,whitney wolfe net worth,John Salley Net Worth; Rochelle Aytes Net Wort...
4,998899,3086809,definition eaves,Eaves are the horizontal section of a roof tha...
...,...,...,...,...
321160,178514,7999994,effects of alcohol on your body,Other short term effects of alcohol include ha...
321161,1093995,2087027,is silicon an alloy,Silicon is a chemical element with symbol Si a...
321162,1083146,7140161,what does racetrack mean,Definition of racetrack for English Language L...
321163,1102407,7209712,"why do auroras form, where do they form, and why?",Auroras are formed when charged particles that...
321164,1102407,7209713,"why do auroras form, where do they form, and why?",What We See. Auroras form in rings centered ov...

In [37]:
qt = "/home/jiit_2404170001/Downloads/job1/gpu-dev-container/validation_test_split/test.tsv"
qvt = pd.read_csv(qt, sep="\t", header=None)
qvt.head()

,0,1,2,3
0,1091630,2079693,phone number of pnc,bank city state routing number; pnc bank. nati...
1,43677,8595669,average salary vice president of real estate,"The average pay for a Vice President (VP), Rea..."
2,1090181,3810789,synonyms enable,Synonym.com is the web's best resource for Eng...
3,529524,1011929,types of rejection,Type I error. When the null hypothesis is true...
4,1070340,5233219,what is a mirror file?,"You may not know what a gesso mirror is, but i..."

In [38]:
qvt.columns = ["query_id", "query", "passage_id", "passage"]

In [39]:
qvt

,query_id,query,passage_id,passage
0,1091630,2079693,phone number of pnc,bank city state routing number; pnc bank. nati...
1,43677,8595669,average salary vice president of real estate,"The average pay for a Vice President (VP), Rea..."
2,1090181,3810789,synonyms enable,Synonym.com is the web's best resource for Eng...
3,529524,1011929,types of rejection,Type I error. When the null hypothesis is true...
4,1070340,5233219,what is a mirror file?,"You may not know what a gesso mirror is, but i..."
...,...,...,...,...
5250608,935672,7969153,when are liquidated damages appropriate,The parties to a contract may specify in the c...
5250609,173168,7997682,does thrush hurt your tongue,heck yea if u scratch it. Oral thrush is painf...
5250610,1087539,7101236,what are iron sites,Iron sights. Iron sights are a system of shape...
5250611,1084600,7126779,what do you mean by meeting minutes?,Meeting minutes is a term used for the notes m...
5250612,1036722,7206869,what is the meaning anal?,Anal retentiveness. The term anal retentive (a...

In [41]:
qvt["query_id"].value_counts()

query_id
593523     104
206007     104
375184     104
883689     104
458013     104
          ...
1088872     19
1090291     16
1088888     15
1025021     13
1088970      7
Name: count, Length: 52378, dtype: int64